// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FSK.Repository.Models;

public partial class Color
{
    public int ColorId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<ElementColor> ElementColors { get; set; } = new List<ElementColor>();

    public virtual ICollection<PatternColor> PatternColors { get; set; } = new List<PatternColor>();
}