// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FSK.Repository.Models;

public partial class Direction
{
    public int DirectionId { get; set; }

    public int GroupId { get; set; }

    public string DirectionName { get; set; }

    public virtual ICollection<Auspiciou> Auspicious { get; set; } = new List<Auspiciou>();

    public virtual DirectionGroup Group { get; set; }

    public virtual ICollection<Inauspiciou> Inauspicious { get; set; } = new List<Inauspiciou>();
}