// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FSK.Repository.Models;

public partial class DirectionGroup
{
    public int GroupId { get; set; }

    public string GroupName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Direction> Directions { get; set; } = new List<Direction>();
}