// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FSK.Repository.Models;

public partial class Element
{
    public int ElementId { get; set; }

    public string Element1 { get; set; }

    public string Description { get; set; }

    public bool Status { get; set; }

    public virtual ICollection<ElementColor> ElementColors { get; set; } = new List<ElementColor>();

    public virtual ICollection<ElementQuantity> ElementQuantities { get; set; } = new List<ElementQuantity>();

    public virtual ICollection<General> Generals { get; set; } = new List<General>();

    public virtual ICollection<Pond> Ponds { get; set; } = new List<Pond>();
}