// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FSK.Repository.Models;

public partial class Kua
{
    public int KuaId { get; set; }

    public string KuaName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Auspiciou> Auspicious { get; set; } = new List<Auspiciou>();

    public virtual ICollection<General> Generals { get; set; } = new List<General>();

    public virtual ICollection<Inauspiciou> Inauspicious { get; set; } = new List<Inauspiciou>();
}