// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FSK.Repository.Models;

public partial class Package
{
    public int PackageId { get; set; }

    public string PackageName { get; set; }

    public decimal? Price { get; set; }

    public virtual ICollection<Advertisement> Advertisements { get; set; } = new List<Advertisement>();

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}