// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FSK.Repository.Models;

public partial class Pattern
{
    public int PatternId { get; set; }

    public int VarietyId { get; set; }

    public string PatternName { get; set; }

    public string ImageUrl { get; set; }

    public virtual ICollection<PatternColor> PatternColors { get; set; } = new List<PatternColor>();

    public virtual Variety Variety { get; set; }
}