// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FSK.Repository.Models;

public partial class Pond
{
    public int PondId { get; set; }

    public int ElementId { get; set; }

    public int ShapeId { get; set; }

    public virtual Element Element { get; set; }

    public virtual Shape Shape { get; set; }
}