// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FSK.Repository.Models;

public partial class Variety
{
    public int VarietyId { get; set; }

    public string VarietyName { get; set; }

    public string ImageUrl { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Pattern> Patterns { get; set; } = new List<Pattern>();
}